language: node_js
cache: yarn
node_js:
  - "12.16.1"
before_script:
  - yarn install --pure-lockfile
  - yarn check --integrity
script:
  - yarn validate-ci
  - env NODE_ICU_DATA=node_modules/full-icu jest --config=./jest.ci.js --runInBand
